#########################
######## server #########
#########################
server:
  port: 8082
########################
######## datasource ####
#####使用jdbc-url，而不是url,否则无法获取数据源
########################
spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/springboot_tutorial
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      jdbc-url: jdbc:mysql://localhost:3306/spring2
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
########################
######## redis ####
########################
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
########################
######## jpa ########
########################
  jpa:
    hibernate:
          ddl-auto: update
########################
######## log多彩输出 ####
########################
  output:
    ansi:
      enabled: detect