#########################
######## server #########
#########################
server:
  port: 8082
########################
######## datasource ####
#####使用jdbc-url，而不是url,否则无法获取数据源
########################
spring:
  datasource:
    primary:
      jdbc-url: jdbc:mysql://localhost:3306/springboot_tutorial
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    secondary:
      jdbc-url: jdbc:mysql://localhost:3306/spring2
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
########################
# 指定加载哪个环境的配置文件#
########################
  profiles:
    active: dev
########################
######## mongo ####
########################
  data:
    mongodb:
      uri: mongodb://localhost:27017/springtutorial
########################
######## redis ####
########################
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
########################
######## jpa ########
########################
  jpa:
    hibernate:
          ddl-auto: update
########################
######## log多彩输出 ####
########################
  output:
    ansi:
      enabled: detect
########################
######## 自定义属性 ####
########################
com:
  example:
    space:
      name: this is author name
      title: springboot实战项目
      desc: ${com.example.space.name}正在写${com.example.space.title}
########################
######## 自定义随机值属性 #
########################
  value: ${random.value}
  number: ${random.int}
  bignumber: ${random.long}
  test1: ${random.int(10)}
  test2: ${random.int[10, 20]}

