#########################
######## server #########
#########################
server:
  port: 8082
########################
######## spring ########
########################
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot_tutorial
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
